
% plots the RANS-RRT* tree loaded by "load_tree.m"

%% load the tree

load_tree();

%% parameters

plot_original_tree = true;
plot_matlab_simulation_of_each_tree_trajectory = true;

%% simulate each individual trajectory using MATLAB

if plot_matlab_simulation_of_each_tree_trajectory
    [Xsim] = simualate_individual_tree_traj(X, U, N, n, m, dt);
end

%% Plot Trees


if plot_original_tree && ~ plot_matlab_simulation_of_each_tree_trajectory
    % plot original tree but do not simulate with matlab
    
    figure();
    title('RANS-RRT* Tree generated by python script')
    hold on;
    for ii = 1:size(X,1)
        xPy = X(ii,:); 
        xPy = reshape(xPy, [n, N+1]);
        plot(xPy(1,:), xPy(2,:), 'b', 'LineWidth', 1);
    end
    
elseif ~plot_original_tree && plot_matlab_simulation_of_each_tree_trajectory
    % plot simulated tree but not original one
    
    figure();
    title('RANS-RRT* Tree with Matlab individual traj sim')
    hold on;
    for ii = 1:size(X,1)
        xMat = Xsim(ii,:);
        xMat = reshape(xMat, [n, N+1]);
        plot(xMat(1,:), xMat(2,:), 'r', 'LineWidth', 1);
    end
    
elseif plot_original_tree && plot_matlab_simulation_of_each_tree_trajectory
    % plot both trees
    
    figure();
    title('RANS-RRT* Python (blue) and Matlab Sim (red) Trees')
    hold on;
    for ii = 1:size(X,1)
        xPy = X(ii,:); 
        xMat = Xsim(ii,:);

        xPy = reshape(xPy, [n, N+1]);
        xMat = reshape(xMat, [n, N+1]);

        plot(xPy(1,:), xPy(2,:), 'b', 'LineWidth', 3);
        plot(xMat(1,:), xMat(2,:), 'r', 'LineWidth', 1);
    end
else
    disp('Nothing to do here')
end
