function [Xsim] = simualate_individual_tree_traj(X, U, N, n, m, dt)
%SIMUALATE_INDIVIDUAL_TREE_TRAJ
% Run 'load_tree.m' before running this. The arguments to this functions
% will be generated by 'load_tree.m'

Xsim = X;

for ii = 1:size(X,1)
    x = X(ii,:); 
    u = U(ii,:); 
    x = reshape(x, [n, N+1]);
    u = reshape(u, [m, N]);
    x_computed = x;

    for jj = 1:N
        xnow = x(:, jj);
        unow = u(:, jj);
        x_computed(:, jj+1) = uni_dyn(xnow,unow,dt);
    end
    x_computed = x_computed(:)';
    Xsim(ii, :) = x_computed;
end

diff = X - Xsim;
worst_error = norm(diff(:), inf);

disp('Worst difference between the Python and Matlab trees is:')
disp(worst_error);

end

